version: '3.9'

services:
  web:
    build: .
    container_name: web-bday
    command: sh -c "alembic upgrade head && uvicorn --factory src.main:create_app --host=0.0.0.0 --port=8000 --use-colors"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8888:8000
  
  db:
    image: postgres:15
    container_name: db-bday
    healthcheck:
      test: pg_isready -d birthday -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data/


volumes:
  pgdbdata: