"""added subs3

Revision ID: e065fedf5af3
Revises: de80de88734f
Create Date: 2024-07-15 01:43:23.372584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e065fedf5af3'
down_revision: Union[str, None] = 'de80de88734f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscribed_to'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    # ### end Alembic commands ###
