"""added unique_subs

Revision ID: 0a80b60b0852
Revises: f6f1453d69d7
Create Date: 2024-07-15 03:48:36.059573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a80b60b0852'
down_revision: Union[str, None] = 'f6f1453d69d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_subs', 'subscriptions', ['subscriber_id', 'subscribed_to_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_subs', 'subscriptions', type_='unique')
    # ### end Alembic commands ###
