"""added subs

Revision ID: 8f7b9f98d6c2
Revises: eced8c9ab392
Create Date: 2024-07-15 01:35:29.560957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7b9f98d6c2'
down_revision: Union[str, None] = 'eced8c9ab392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_date_of_birth'), 'users', ['date_of_birth'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_date_of_birth'), table_name='users')
    # ### end Alembic commands ###
