"""changed subs

Revision ID: f6f1453d69d7
Revises: e065fedf5af3
Create Date: 2024-07-15 02:05:53.752305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f1453d69d7'
down_revision: Union[str, None] = 'e065fedf5af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('subscribed_to_id', sa.Integer(), nullable=False))
    op.drop_constraint('subscriptions_subscriber_id_subscribed_to_key', 'subscriptions', type_='unique')
    op.drop_constraint('subscriptions_subscribed_to_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscribed_to_id'], ['id'])
    op.drop_column('subscriptions', 'subscribed_to')
    op.drop_column('subscriptions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('subscriptions', sa.Column('subscribed_to', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_subscribed_to_fkey', 'subscriptions', 'users', ['subscribed_to'], ['id'])
    op.create_unique_constraint('subscriptions_subscriber_id_subscribed_to_key', 'subscriptions', ['subscriber_id', 'subscribed_to'])
    op.drop_column('subscriptions', 'subscribed_to_id')
    # ### end Alembic commands ###
